### PR TITLE
Support Unix domain sockets

### PR DESCRIPTION
**Pull request by bblancha**
Add options to client and serverbuilder for generating servers/clients
which use Unix domain sockets.

Addresses #91

### CODE REVIEW

**Comment by bblancha** [comment]
Note: This won't successfully build until a new version of httpbis is released.
I tested locally by manually pointing grpc/Cargo.toml to master of rust-http2.

**Comment by przygienda** [comment]
So what happened here. httpbis has pulled in the changes but this pullup stagnated?

**Comment by bblancha** [comment]
Yes, originally this PR was waiting on the next httbis release, but things slowed down and I did not revisit it.

If it is to be picked back up again, it should probably be redone with impl traits

**Comment by przygienda** [comment]
awfully quiet, I probably grab a new branch (this one got deleted?) and apply your patch, roll it forward ...

**Comment by bblancha** [comment]
Yes, sounds good. 
Let me know if there are problems resolving the conflicts, and I will take a look.
I haven't followed this project in a while, so I'm not sure what the changes look like.

**Pull request closed without merging**
